### ISSUE TITLE
Plans to publish the plugin?

### ISSUE THREAD

**Issue by chuac** [la-haus/iterable-flutter#23]
Hi there, 

I'm currently unable to add this plugin as a dependency in my pubspec.yaml file as it hasn't been published yet. Are there any plans to publish to pub.dev soon?

Thanks!

**Comment by cdmunoz** [comment]
Hi @chuac 

As the plugin is still in development phase, we have no plans to publish it in the short term, because it's focused mainly in our use case and probably some small things can be changing, although you can use it to init the SDK, do single tracking and identify.

In the meantime you can use it the way we are doing it, through one of our [releases](https://github.com/la-haus/iterable-flutter/releases):

```bash
# pubspec.yaml

iterable_flutter:
    git:
      url: https://github.com/la-haus/iterable-flutter.git
      ref: 0.1.0
```

**Comment by chuac** [comment]
Awesome, that worked! Thank you for the prompt response.
