### ISSUE TITLE
Update User Function

### ISSUE THREAD

**Issue by Gabriel-Azevedo** [la-haus/iterable-flutter#28]
Hello,

First of all, thanks for creating this package. I created one for my company but I like yours better. I'm still testing all the functionalities but so far so good.

One thing missing for me is the updateUser function from the SDK.

I went ahead and created a branch with this feature, but I don't have permission to push it to open a pull request.

Let me know if that's something you guys are interested in, otherwise, I can clone the repo.

Cheers,
Gabe

**Comment by danielgomezrico** [comment]
@Gabriel-Azevedo thanks for that! we are happy to hear that and give some hints, so you can contribute. 

In order to create a PR you need to fork this repository and then push the branch to your fork, then open a PR from that fork to this one is totally allowed.

Let us know if that process worked well for you

**Comment by Gabriel-Azevedo** [comment]
Thanks for all the help.

Merged on https://github.com/la-haus/iterable-flutter/pull/31
