### ISSUE TITLE
Why is registerForPush N/A for iOS

### ISSUE THREAD

**Issue by tobinharris** [la-haus/iterable-flutter#29]
Hi 

Thanks for creating this library 🙌 

Out of interest, why is `registerForPush` NA for iOS?

**Comment by cdmunoz** [comment]
Hi @tobinharris 
This is because for iOS, unlike Android, when setting email or user id, the SDK automatically fetches its token from Apple (if all previous setup is correct). Let me share to you [some important parts of the official SDK documentation for Iterable iOS.](https://support.iterable.com/hc/en-us/articles/360035018152-Iterable-s-iOS-SDK-#_7-4-fetch-a-device-token-from-apple-and-register-it-with-iterable)
If you need further information, let us know.
