### ISSUE TITLE
Allow Provisional push on iOS?

### ISSUE THREAD

**Issue by tobinharris** [la-haus/iterable-flutter#30]
Have you considered supporting provisional push? This prevents the "Allow Push" popup and lets the user decide what to do when they receive their first push.

It would mean a change [here](https://github.com/la-haus/iterable-flutter/blob/e382e4b71d5dfd1d50b8a5ef4eb1f777334ca757/ios/Classes/SwiftIterableFlutterPlugin.swift#L80) to be like `.requestAuthorization(options: [.alert, .sound, .badge, .provisional])`.

[This article](https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications) gives a good overview.

**Comment by cdmunoz** [comment]
Hi @tobinharris 
The current implementation obeys the particular requirements of our company's internal projects and we decided to open source it because currently there are no Iterable's Flutter SDK and we are happy to help others and then did the first step with this. 
Feel free to fork the project and make a PR with your suggestions taking into consideration that new changes are not breaking ones as far as possible, then our team can check it and make a decision about it. 😄

**Comment by Santi92** [comment]
Hi @tobinharris 

In version ref: 0.3.0 you can already request when you want the push permission, it is no longer mandatory.

 ```yaml
  dependencies:
  iterable_flutter: ^0.3.0+1
````
I hope you update and confirm me to close this issue.
